# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '79604af7-679a-47e1-a9b3-dc46157eb410'

  # Web app name
  webAppName: 'DLib'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: ''

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.11'
 #132

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m unittest discover
  displayName: 'Run unit tests'

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: 'flask-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: $(azureServiceConnectionId)
    appName:  $(webAppName)
    containers: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip