# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '79604af7-679a-47e1-a9b3-dc46157eb410'

  # Web app name
  webAppName: 'DLib'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: ''

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  pythonVersion: '3.11'

pool:
  name: mypc
  demands:
  - Agent.OS -equals Windows_NT

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.4'
    addToPath: true

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m unittest discover
  displayName: 'Run unit tests'

- script: docker build -t flask-app:latest .
  displayName: 'Build Docker Image'

- script: docker run -d -p 5000:5000 flask-app:latest
  displayName: 'Run Docker Container'